

services:
  postgres:
    image: postgres
    ports:
     - 5432:5432
    environment:
      - POSTGRES_PASSWORD=rahul
    networks:
      - host
  user_app:
    build: 
      context: ./
      dockerfile: Dockerfile
    networks:
      - host
    environment:
      DATABASE_URL: postgresql://postgres:rahul@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

networks:
  host:
    driver: bridge